
version: 2


models:
    - name: covid19
      description: "A model of latest stats for covid19"
      columns:
          - name: iso_code
            description: "The country code"
            tests:
              - unique
              - not_null

    - name: population
      description: "A starter dbt model"
      columns:
          - name: Code
            description: "The primary key for this table"
            tests:
              - not_null
